### ISSUE TITLE
Erro ao inserir novo grupo

### ISSUE THREAD

**Issue by jonasdiel** [EstacioneFacil/sistema#26]
Ao inserir um novo grupo, ocorre o seguinte erro:

`01:20:42 DEBUG [SQL                 ] select this_.id as id1_5_0_, this_.descricao as descrica2_5_0_ from grupo_permissao this_
Exception in thread "AWT-EventQueue-0" org.hibernate.QueryException: could not resolve property: acao of: model.Menu
	at org.hibernate.persister.entity.AbstractPropertyMapping.propertyException(AbstractPropertyMapping.java:83)
	at org.hibernate.persister.entity.AbstractPropertyMapping.toType(AbstractPropertyMapping.java:77)
	at org.hibernate.persister.entity.AbstractEntityPersister.getSubclassPropertyTableNumber(AbstractEntityPersister.java:1995)
	at org.hibernate.persister.entity.BasicEntityPropertyMapping.toColumns(BasicEntityPropertyMapping.java:61)
	at org.hibernate.persister.entity.AbstractEntityPersister.toColumns(AbstractEntityPersister.java:1970)`

**Comment by douglashauschild** [comment]
"could not resolve property: acao of: model.Menu"

Não foi encontrado a propriedade acao na classe Menu.
Foi alterado algumas coisas nessa classe.
